"""qds reference tables (task 0.3, handbook §6.5 / §7.2)

Creates the `qds` schema and its eight import-generated reference tables. This
is an **expand-only** migration: it adds structures and drops nothing, so it is
safe to run ahead of the deploy that starts reading them (expand → migrate →
contract, §7.3).

The DDL is autogenerated from `qc_shared.qds.tables` — the single definition the
API reads and `tools/pack-builder` writes. Do not hand-edit the table bodies
here; change the shared metadata and regenerate, or the two will drift.

Runtime writes: none. `qds.*` is rebuilt only by the pack-builder import, and
the API opens read-only transactions against it (`app.core.db.qds_connection`).

Revision ID: 0001_qds
Revises:
Create Date: 2026-07-25
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import CreateSchema, DropSchema

revision: str = '0001_qds'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

SCHEMA = 'qds'


def upgrade() -> None:
    op.execute(CreateSchema(SCHEMA, if_not_exists=True))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset',
    sa.Column('item', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('checksum', sa.String(length=71), nullable=False),
    sa.Column('pack_id', sa.String(length=64), nullable=True),
    sa.Column('pack_version', sa.String(length=16), nullable=True),
    sa.Column('row_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('imported_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("checksum LIKE 'sha256:%'", name=op.f('ck_dataset_checksum_algorithm')),
    sa.PrimaryKeyConstraint('item', name=op.f('pk_dataset')),
    schema='qds',
    comment='Provenance of every imported qds dataset item (§6.4 licensing gate joins on `item`).'
    )
    op.create_table('mushaf',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('script', sa.String(length=32), nullable=False),
    sa.Column('page_count', sa.SmallInteger(), nullable=False),
    sa.Column('lines_per_page', sa.SmallInteger(), nullable=False),
    sa.Column('dataset_item', sa.String(length=64), nullable=False),
    sa.CheckConstraint('page_count > 0', name=op.f('ck_mushaf_page_count_positive')),
    sa.ForeignKeyConstraint(['dataset_item'], ['qds.dataset.item'], name=op.f('fk_mushaf_dataset_item_dataset')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mushaf')),
    schema='qds',
    comment='One row per layout edition shipped by a data pack.'
    )
    op.create_table('translation_resource',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('translator', sa.Text(), nullable=True),
    sa.Column('direction', sa.String(length=3), nullable=False),
    sa.Column('is_word_by_word', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('dataset_item', sa.String(length=64), nullable=False),
    sa.CheckConstraint("direction IN ('ltr', 'rtl')", name=op.f('ck_translation_resource_direction_enum')),
    sa.ForeignKeyConstraint(['dataset_item'], ['qds.dataset.item'], name=op.f('fk_translation_resource_dataset_item_dataset')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_translation_resource')),
    schema='qds',
    comment='Metadata for translation/gloss resources; translation bodies land in a later phase.'
    )
    op.create_table('verse',
    sa.Column('surah', sa.SmallInteger(), nullable=False),
    sa.Column('ayah', sa.SmallInteger(), nullable=False),
    sa.Column('text_uthmani', sa.Text(), nullable=False),
    sa.Column('word_count', sa.SmallInteger(), nullable=False),
    sa.Column('dataset_item', sa.String(length=64), nullable=False),
    sa.CheckConstraint('ayah >= 1', name=op.f('ck_verse_ayah_positive')),
    sa.CheckConstraint('surah BETWEEN 1 AND 114', name=op.f('ck_verse_surah_range')),
    sa.CheckConstraint('word_count >= 1', name=op.f('ck_verse_word_count_positive')),
    sa.ForeignKeyConstraint(['dataset_item'], ['qds.dataset.item'], name=op.f('fk_verse_dataset_item_dataset')),
    sa.PrimaryKeyConstraint('surah', 'ayah', name=op.f('pk_verse')),
    schema='qds',
    comment='Canonical ayah text, addressed by (surah, ayah) per §6.1.'
    )
    op.create_table('page_line',
    sa.Column('mushaf_id', sa.String(length=64), nullable=False),
    sa.Column('page', sa.SmallInteger(), nullable=False),
    sa.Column('line_number', sa.SmallInteger(), nullable=False),
    sa.Column('line_type', sa.String(length=16), nullable=False),
    sa.Column('surah', sa.SmallInteger(), nullable=True),
    sa.Column('word_count', sa.SmallInteger(), server_default='0', nullable=False),
    sa.CheckConstraint("(line_type = 'ayah') = (surah IS NULL)", name=op.f('ck_page_line_surah_only_on_heading_lines')),
    sa.CheckConstraint("line_type IN ('ayah', 'surah_name', 'basmallah')", name=op.f('ck_page_line_line_type_enum')),
    sa.CheckConstraint('line_number >= 1', name=op.f('ck_page_line_line_number_positive')),
    sa.CheckConstraint('page >= 1', name=op.f('ck_page_line_page_positive')),
    sa.ForeignKeyConstraint(['mushaf_id'], ['qds.mushaf.id'], name=op.f('fk_page_line_mushaf_id_mushaf')),
    sa.PrimaryKeyConstraint('mushaf_id', 'page', 'line_number', name=op.f('pk_page_line')),
    schema='qds',
    comment='Complete typeset line inventory of every page, including word-less heading lines.'
    )
    op.create_table('word',
    sa.Column('surah', sa.SmallInteger(), nullable=False),
    sa.Column('ayah', sa.SmallInteger(), nullable=False),
    sa.Column('word_position', sa.SmallInteger(), nullable=False),
    sa.Column('text_uthmani', sa.Text(), nullable=False),
    sa.Column('transliteration', sa.Text(), nullable=True),
    sa.Column('morphology_ref', sa.String(length=32), nullable=True),
    sa.Column('dataset_item', sa.String(length=64), nullable=False),
    sa.CheckConstraint('word_position >= 1', name=op.f('ck_word_word_position_positive')),
    sa.ForeignKeyConstraint(['dataset_item'], ['qds.dataset.item'], name=op.f('fk_word_dataset_item_dataset')),
    sa.ForeignKeyConstraint(['surah', 'ayah'], ['qds.verse.surah', 'qds.verse.ayah'], name='fk_word_verse'),
    sa.PrimaryKeyConstraint('surah', 'ayah', 'word_position', name=op.f('pk_word')),
    schema='qds',
    comment='Word-level text addressed by (surah, ayah, word_position) per §6.1.'
    )
    op.create_table('word_gloss',
    sa.Column('surah', sa.SmallInteger(), nullable=False),
    sa.Column('ayah', sa.SmallInteger(), nullable=False),
    sa.Column('word_position', sa.SmallInteger(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('gloss', sa.Text(), nullable=False),
    sa.Column('dataset_item', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['dataset_item'], ['qds.dataset.item'], name=op.f('fk_word_gloss_dataset_item_dataset')),
    sa.ForeignKeyConstraint(['surah', 'ayah', 'word_position'], ['qds.word.surah', 'qds.word.ayah', 'qds.word.word_position'], name='fk_word_gloss_word'),
    sa.PrimaryKeyConstraint('surah', 'ayah', 'word_position', 'language', name=op.f('pk_word_gloss')),
    schema='qds',
    comment='Word-by-word gloss, one row per (word key, language). Packs ship one language at a time.'
    )
    op.create_table('word_placement',
    sa.Column('mushaf_id', sa.String(length=64), nullable=False),
    sa.Column('surah', sa.SmallInteger(), nullable=False),
    sa.Column('ayah', sa.SmallInteger(), nullable=False),
    sa.Column('word_position', sa.SmallInteger(), nullable=False),
    sa.Column('page', sa.SmallInteger(), nullable=False),
    sa.Column('line_number', sa.SmallInteger(), nullable=False),
    sa.Column('line_ordinal', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['mushaf_id', 'page', 'line_number'], ['qds.page_line.mushaf_id', 'qds.page_line.page', 'qds.page_line.line_number'], name='fk_word_placement_page_line'),
    sa.ForeignKeyConstraint(['mushaf_id'], ['qds.mushaf.id'], name=op.f('fk_word_placement_mushaf_id_mushaf')),
    sa.ForeignKeyConstraint(['surah', 'ayah', 'word_position'], ['qds.word.surah', 'qds.word.ayah', 'qds.word.word_position'], name='fk_word_placement_word'),
    sa.PrimaryKeyConstraint('mushaf_id', 'surah', 'ayah', 'word_position', name=op.f('pk_word_placement')),
    sa.UniqueConstraint('mushaf_id', 'page', 'line_number', 'line_ordinal', name='uq_word_placement_line_slot'),
    schema='qds',
    comment='The §6.1 word_key → (mushaf_id, page, line) mapping that ships in the data pack.'
    )
    op.create_index('ix_word_placement_page', 'word_placement', ['mushaf_id', 'page', 'line_number', 'line_ordinal'], unique=False, schema='qds')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_word_placement_page', table_name='word_placement', schema='qds')
    op.drop_table('word_placement', schema='qds')
    op.drop_table('word_gloss', schema='qds')
    op.drop_table('word', schema='qds')
    op.drop_table('page_line', schema='qds')
    op.drop_table('verse', schema='qds')
    op.drop_table('translation_resource', schema='qds')
    op.drop_table('mushaf', schema='qds')
    op.drop_table('dataset', schema='qds')
    # ### end Alembic commands ###
    op.execute(DropSchema(SCHEMA, if_exists=True))
